<a href="https://colab.research.google.com/github/MamidiPravallikaReddy/ML-LAB/blob/main/ML(week4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
from pathlib import Path

In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/house_price_train.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
df.shape

(1460, 81)

In [4]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [5]:
[col for col in df.columns if df[col].isnull().sum()]

['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature']

In [6]:
df = df.drop(columns=['LotFrontage',
 'Alley',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature'])

In [7]:
[col for col in df.columns if df[col].isnull().sum()]

[]

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split

X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape)

(1168, 189) (292, 189)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

sfs1 = SFS(RandomForestRegressor(),
           k_features=5,
           forward=True,
           floating=False,
           verbose=2,
           scoring='r2',
           cv=3)
sfs1 = sfs1.fit(np.array(X_train), y_train)
X_train.columns[list(sfs1.k_feature_idx_)]

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:   18.4s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:  1.0min
[Parallel(n_jobs=1)]: Done 189 out of 189 | elapsed:  1.2min finished

[2025-08-19 15:13:32] Features: 1/5 -- score: 0.6644851285040098[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:   17.4s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:  1.0min
[Parallel(n_jobs=1)]: Done 188 out of 188 | elapsed:  1.2min finished

[2025-08-19 15:14:44] Features: 2/5 -- score: 0.7175495968014669[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:   28.3s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:  1.8min
[Parallel(n_jobs=1)]: Done 187 out of 187 | elapsed:  2.1min finished

[2025-08-19 15:16:49] Features: 3/5 -- score: 0.7941286721681714[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:   33.6s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:  2.2min
[Parallel(n_jobs=1)]: Done 186 out of 186 | elapsed:  2.5min finished

[2025-08-19 15:19:20] Features: 4/5 -- score: 0.8359826312204198[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:   38.5s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:  2.5min
[Parallel(n_jobs=1)]: Done 185 out of 185 | elapsed:  2.9min finished

[2025-08-19 15:22:14] Features: 5/5 -- score: 0.8475655510202703

Index(['OverallQual', 'OverallCond', 'YearBuilt', 'BsmtFinSF1', 'GrLivArea'], dtype='object')

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

sfs1 = SFS(RandomForestRegressor(),
           k_features=5,
           forward=False,
           floating=False,
           verbose=2,
           scoring='r2',
           cv=3)
sfs1 = sfs1.fit(np.array(X_train), y_train)
X_train.columns[list(sfs1.k_feature_idx_)]

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  3.2min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 12.9min
[Parallel(n_jobs=1)]: Done 189 out of 189 | elapsed: 15.1min finished

[2025-08-19 15:38:17] Features: 188/5 -- score: 0.8603180635043639[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  3.1min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 12.4min
[Parallel(n_jobs=1)]: Done 188 out of 188 | elapsed: 14.5min finished

[2025-08-19 15:52:45] Features: 187/5 -- score: 0.8617592149647088[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  3.0min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 12.1min
[Parallel(n_jobs=1)]: Done 187 out of 187 | elapsed: 14.0min finished

[2025-08-19 16:06:46] Features: 186/5 -- score: 0.8626293539422109[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  3.0min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 12.2min
[Parallel(n_jobs=1)]: Done 186 out of 186 | elapsed: 14.1min finished

[2025-08-19 16:20:50] Features: 185/5 -- score: 0.8621670176337547[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  3.0min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.9min
[Parallel(n_jobs=1)]: Done 185 out of 185 | elapsed: 13.6min finished

[2025-08-19 16:34:29] Features: 184/5 -- score: 0.8626844092604613[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.9min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.7min
[Parallel(n_jobs=1)]: Done 184 out of 184 | elapsed: 13.4min finished

[2025-08-19 16:47:52] Features: 183/5 -- score: 0.8635882702978103[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.9min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.7min
[Parallel(n_jobs=1)]: Done 183 out of 183 | elapsed: 13.3min finished

[2025-08-19 17:01:08] Features: 182/5 -- score: 0.8621980527867988[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.9min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.6min
[Parallel(n_jobs=1)]: Done 182 out of 182 | elapsed: 13.1min finished

[2025-08-19 17:14:14] Features: 181/5 -- score: 0.862871556010186[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.9min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.6min
[Parallel(n_jobs=1)]: Done 181 out of 181 | elapsed: 13.0min finished

[2025-08-19 17:27:13] Features: 180/5 -- score: 0.863131060997259[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.9min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.5min
[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed: 12.8min finished

[2025-08-19 17:40:04] Features: 179/5 -- score: 0.8630625989434756[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:  2.8min
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed: 11.5min
[Parallel(n_jobs=1)]: Done 179 out of 179 | elapsed: 12.7min finished

[2025-08-19 17:52:47] Features: 178/5 -- score: 0.8622521926538088

In [ ]:
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS

data = load_diabetes()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(random_state=42)

efs = EFS(estimator=model,
          min_features=1,
          max_features=4,
          scoring='r2',
          cv=5)

efs = efs.fit(X_train, y_train)

print('Best R2 score: %.2f' % efs.best_score_)
print('Best subset (indices):', efs.best_idx_)
print('Best subset (corresponding names):', efs.best_feature_names_)

efs_results = pd.DataFrame.from_dict(efs.get_metric_dict()).T
efs_results.sort_values(by='avg_score', ascending=False, inplace=True)

print(efs_results.head())

Features: 385/385

Best R2 score: 0.38
Best subset (indices): (2, 5, 8, 9)
Best subset (corresponding names): ('bmi', 's2', 's5', 's6')
      feature_idx                                          cv_scores  \
345  (2, 5, 8, 9)  [0.5398434979052924, 0.11657729430834629, 0.45...
139     (2, 8, 9)  [0.5584771360414856, 0.08081416523573492, 0.41...
349  (2, 7, 8, 9)  [0.5850705935289853, 0.04646998292164928, 0.41...
339  (2, 4, 8, 9)  [0.526273378104205, 0.09946924577683958, 0.489...
329  (2, 3, 8, 9)  [0.5090316440065242, 0.06677410931376138, 0.39...

    avg_score      feature_names  ci_bound   std_dev   std_err
345  0.378185  (bmi, s2, s5, s6)  0.216638  0.168551  0.084276
139  0.375509      (bmi, s5, s6)  0.234757  0.182649  0.091325
349  0.375486  (bmi, s4, s5, s6)  0.250887  0.195198  0.097599
339  0.372337  (bmi, s1, s5, s6)  0.249236  0.193914  0.096957
329  0.371834  (bmi, bp, s5, s6)  0.216425  0.168386  0.084193

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.model_selection import KFold

model = RandomForestRegressor()


rfecv = RFECV(estimator=model, step=1, cv=KFold(3), scoring='r2')
rfecv.fit(np.array(X_train), y_train)

selected_features = X_train.columns[rfecv.support_]
print("Optimal number of features:", rfecv.n_features_)
print("Selected features:", selected_features)

Optimal number of features: 9
Selected features: Index(['age', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [30]:
df1=pd.read_csv('/content/drive/MyDrive/titanic_train.csv')
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [32]:
df1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Cabin',
       'Embarked'],
      dtype='object')

In [31]:
df1=df1.drop(['PassengerId','Name','Ticket'],axis=1)

In [33]:
df1.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [35]:
[col for col in df1.columns if df1[col].isnull().sum()>0]

['Age', 'Cabin', 'Embarked']

In [36]:
df1['Age'] = df1['Age'].fillna(df1['Age'].median())

In [37]:
df1=df1.drop(['Embarked','Cabin'],axis=1)

In [38]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import roc_auc_score
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.model_selection import train_test_split
X = df1.drop('Survived',axis=1)
y = df1['Survived']
X = pd.get_dummies(X,drop_first=True)

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [39]:
grouped_feature_ls = []
correlated_groups = []
def correlation (dataset, threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:
                colname=corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr
corr_features=correlation (x_test, 0.9)
correlated_features = set(corr_features)
print(len(correlated_features))

0

In [40]:
sfs1=SFS(RandomForestClassifier(n_jobs=4),k_features=5,forward=True,verbose=2,scoring='roc_auc' or 'accuracy',cv=3)

In [41]:
sfs1=sfs1.fit(np.array(x_train.fillna(0)),y_train)

[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    3.7s finished

[2025-08-20 04:20:22] Features: 1/5 -- score: 0.765194136612553[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    3.7s finished

[2025-08-20 04:20:26] Features: 2/5 -- score: 0.832223720877483[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    2.4s finished

[2025-08-20 04:20:29] Features: 3/5 -- score: 0.8382639091409869[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.9s finished

[2025-08-20 04:20:30] Features: 4/5 -- score: 0.8437728848708727[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    1.3s finished

[2025-08-20 04:20:32] Features: 5/5 -- score: 0.8439754058520462

In [42]:
print('best accracy score',sfs1.k_score_)
print('best subset(indices)',sfs1.k_feature_idx_)
print('Best subset (corresponding names):', sfs1.k_feature_names_)

best accracy score 0.8439754058520462
best subset(indices) (0, 1, 3, 4, 5)
Best subset (corresponding names): ('0', '1', '3', '4', '5')

In [43]:
sfs2=SFS(RandomForestClassifier(n_jobs=4),k_features=5,forward=False,verbose=2,scoring='roc_auc' or 'accuracy',cv=3)
sfs2=sfs2.fit(np.array(x_train.fillna(0)),y_train)
print('best accracy score',sfs2.k_score_)
print('best subset(indices)',sfs2.k_feature_idx_)
print('Best subset (corresponding names):', sfs2.k_feature_names_)

best accracy score 0.8438413369625093
best subset(indices) (0, 1, 3, 4, 5)
Best subset (corresponding names): ('0', '1', '3', '4', '5')

[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:    3.8s finished

[2025-08-20 04:20:42] Features: 5/5 -- score: 0.8438413369625093

In [44]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
efs=EFS(RandomForestClassifier(n_jobs=4),min_features=1,max_features=4,scoring='accuracy',cv=5)
efs=efs.fit(x_train,y_train)
print('best accuracy score',efs.best_score_)
print('best subset(indices)',efs.best_idx_)
print('Best subset (corresponding names):', efs.best_feature_names_)

Features: 56/56

best accuracy score 0.8106322580645162
best subset(indices) (0, 1, 3, 5)
Best subset (corresponding names): ('Pclass', 'Age', 'Parch', 'Sex_male')

In [45]:
efs_results = pd.DataFrame.from_dict(efs.get_metric_dict()).T
efs_results.sort_values(by='avg_score', ascending=True, inplace=True)
efs_results

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(1,)","[0.6, 0.56, 0.6, 0.5725806451612904, 0.5887096...",0.584258,"(Age,)",0.020243,0.01575,0.007875
12,"(1, 3)","[0.56, 0.576, 0.648, 0.6290322580645161, 0.596...",0.601961,"(Age, Parch)",0.041901,0.032601,0.0163
11,"(1, 2)","[0.648, 0.568, 0.632, 0.5564516129032258, 0.62...",0.605084,"(Age, SibSp)",0.046551,0.036218,0.018109
3,"(3,)","[0.568, 0.6, 0.616, 0.6048387096774194, 0.6451...",0.6068,"(Parch,)",0.032064,0.024947,0.012473
34,"(1, 3, 4)","[0.576, 0.632, 0.616, 0.5967741935483871, 0.62...",0.608348,"(Age, Parch, Fare)",0.025432,0.019787,0.009893
13,"(1, 4)","[0.608, 0.632, 0.592, 0.5725806451612904, 0.64...",0.609948,"(Age, Fare)",0.033755,0.026262,0.013131
31,"(1, 2, 3)","[0.632, 0.584, 0.68, 0.5887096774193549, 0.604...",0.61791,"(Age, SibSp, Parch)",0.045359,0.035291,0.017645
2,"(2,)","[0.624, 0.6, 0.656, 0.5645161290322581, 0.7177...",0.632452,"(SibSp,)",0.066955,0.052094,0.026047
21,"(0, 1, 2)","[0.616, 0.632, 0.704, 0.6048387096774194, 0.65...",0.642013,"(Pclass, Age, SibSp)",0.044992,0.035006,0.017503
51,"(1, 2, 3, 4)","[0.664, 0.64, 0.632, 0.6290322580645161, 0.645...",0.642039,"(Age, SibSp, Parch, Fare)",0.01591,0.012379,0.006189
42,"(0, 1, 2, 4)","[0.672, 0.656, 0.632, 0.6048387096774194, 0.67...",0.648452,"(Pclass, Age, SibSp, Fare)",0.0346,0.02692,0.01346
23,"(0, 1, 4)","[0.648, 0.664, 0.672, 0.6129032258064516, 0.66...",0.651639,"(Pclass, Age, Fare)",0.026802,0.020853,0.010426
32,"(1, 2, 4)","[0.672, 0.664, 0.672, 0.5967741935483871, 0.66...",0.653213,"(Age, SibSp, Fare)",0.036683,0.028541,0.01427
0,"(0,)","[0.64, 0.656, 0.68, 0.6693548387096774, 0.6290...",0.654877,"(Pclass,)",0.023917,0.018608,0.009304
44,"(0, 1, 3, 4)","[0.64, 0.648, 0.68, 0.6532258064516129, 0.6532...",0.65489,"(Pclass, Age, Parch, Fare)",0.017294,0.013455,0.006728
41,"(0, 1, 2, 3)","[0.616, 0.632, 0.752, 0.6370967741935484, 0.64...",0.656452,"(Pclass, Age, SibSp, Parch)",0.062613,0.048715,0.024358
16,"(2, 4)","[0.656, 0.672, 0.688, 0.6451612903225806, 0.63...",0.659652,"(SibSp, Fare)",0.023617,0.018375,0.009187
6,"(0, 1)","[0.64, 0.68, 0.68, 0.6209677419354839, 0.68548...",0.66129,"(Pclass, Age)",0.033341,0.025941,0.01297
22,"(0, 1, 3)","[0.592, 0.672, 0.728, 0.6612903225806451, 0.65...",0.661303,"(Pclass, Age, Parch)",0.055821,0.043431,0.021715
7,"(0, 2)","[0.664, 0.672, 0.688, 0.6774193548387096, 0.61...",0.662865,"(Pclass, SibSp)",0.033637,0.026171,0.013085
15,"(2, 3)","[0.648, 0.64, 0.72, 0.6209677419354839, 0.6854...",0.66289,"(SibSp, Parch)",0.045533,0.035426,0.017713
18,"(3, 4)","[0.672, 0.64, 0.68, 0.6451612903225806, 0.7016...",0.667755,"(Parch, Fare)",0.029282,0.022782,0.011391
25,"(0, 2, 3)","[0.648, 0.696, 0.672, 0.6693548387096774, 0.68...",0.674168,"(Pclass, SibSp, Parch)",0.020862,0.016232,0.008116
26,"(0, 2, 4)","[0.688, 0.656, 0.72, 0.6612903225806451, 0.661...",0.677316,"(Pclass, SibSp, Fare)",0.030976,0.0241,0.01205
37,"(2, 3, 4)","[0.72, 0.672, 0.68, 0.6532258064516129, 0.6693...",0.678916,"(SibSp, Parch, Fare)",0.028673,0.022308,0.011154
4,"(4,)","[0.688, 0.664, 0.672, 0.6935483870967742, 0.68...",0.680606,"(Fare,)",0.01403,0.010916,0.005458
47,"(0, 2, 3, 4)","[0.68, 0.68, 0.712, 0.6612903225806451, 0.6774...",0.682142,"(Pclass, SibSp, Parch, Fare)",0.02118,0.016479,0.008239
9,"(0, 4)","[0.68, 0.664, 0.72, 0.6935483870967742, 0.7016...",0.691832,"(Pclass, Fare)",0.024432,0.019009,0.009504
28,"(0, 3, 4)","[0.68, 0.68, 0.72, 0.6854838709677419, 0.70161...",0.693419,"(Pclass, Parch, Fare)",0.019885,0.015471,0.007736
8,"(0, 3)","[0.672, 0.704, 0.736, 0.6935483870967742, 0.70...",0.703045,"(Pclass, Parch)",0.026868,0.020904,0.010452
36,"(1, 4, 5)","[0.712, 0.784, 0.728, 0.7419354838709677, 0.79...",0.752865,"(Age, Fare, Sex_male)",0.042431,0.033013,0.016507
54,"(1, 3, 4, 5)","[0.704, 0.792, 0.76, 0.75, 0.7983870967741935]",0.760877,"(Age, Parch, Fare, Sex_male)",0.043509,0.033852,0.016926
10,"(0, 5)","[0.752, 0.8, 0.768, 0.75, 0.75]",0.764,"(Pclass, Sex_male)",0.02471,0.019225,0.009612
35,"(1, 3, 5)","[0.744, 0.784, 0.744, 0.7580645161290323, 0.80...",0.767303,"(Age, Parch, Sex_male)",0.031393,0.024425,0.012212
53,"(1, 2, 4, 5)","[0.736, 0.792, 0.76, 0.7661290322580645, 0.790...",0.76889,"(Age, SibSp, Fare, Sex_male)",0.026726,0.020793,0.010397
55,"(2, 3, 4, 5)","[0.728, 0.84, 0.776, 0.7580645161290323, 0.758...",0.772026,"(SibSp, Parch, Fare, Sex_male)",0.047969,0.037321,0.018661
52,"(1, 2, 3, 5)","[0.736, 0.736, 0.776, 0.8064516129032258, 0.80...",0.772181,"(Age, SibSp, Parch, Sex_male)",0.04057,0.031565,0.015782
39,"(2, 4, 5)","[0.76, 0.824, 0.784, 0.7580645161290323, 0.75]",0.775213,"(SibSp, Fare, Sex_male)",0.034577,0.026902,0.013451
14,"(1, 5)","[0.736, 0.824, 0.72, 0.782258064516129, 0.8145...",0.775355,"(Age, Sex_male)",0.053182,0.041378,0.020689
38,"(2, 3, 5)","[0.784, 0.792, 0.752, 0.75, 0.8064516129032258]",0.77689,"(SibSp, Parch, Sex_male)",0.028713,0.02234,0.01117
40,"(3, 4, 5)","[0.744, 0.84, 0.768, 0.75, 0.7903225806451613]",0.778465,"(Parch, Fare, Sex_male)",0.044653,0.034741,0.017371
48,"(0, 2, 3, 5)","[0.792, 0.792, 0.776, 0.7419354838709677, 0.79...",0.780065,"(Pclass, SibSp, Parch, Sex_male)",0.026284,0.02045,0.010225
33,"(1, 2, 5)","[0.728, 0.752, 0.768, 0.8145161290322581, 0.83...",0.780245,"(Age, SibSp, Sex_male)",0.052272,0.040669,0.020335
19,"(3, 5)","[0.752, 0.8, 0.768, 0.7903225806451613, 0.8064...",0.783355,"(Parch, Sex_male)",0.026202,0.020386,0.010193
20,"(4, 5)","[0.744, 0.824, 0.784, 0.8064516129032258, 0.77...",0.786529,"(Fare, Sex_male)",0.035285,0.027453,0.013726
5,"(5,)","[0.752, 0.8, 0.768, 0.7983870967741935, 0.8145...",0.786581,"(Sex_male,)",0.029539,0.022982,0.011491
50,"(0, 3, 4, 5)","[0.744, 0.832, 0.8, 0.7741935483870968, 0.7983...",0.789716,"(Pclass, Parch, Fare, Sex_male)",0.037691,0.029325,0.014663
27,"(0, 2, 5)","[0.776, 0.792, 0.776, 0.8064516129032258, 0.81...",0.792994,"(Pclass, SibSp, Sex_male)",0.020101,0.015639,0.007819
17,"(2, 5)","[0.76, 0.792, 0.768, 0.8145161290322581, 0.830...",0.793032,"(SibSp, Sex_male)",0.034464,0.026815,0.013407
29,"(0, 3, 5)","[0.776, 0.816, 0.792, 0.7580645161290323, 0.83...",0.796155,"(Pclass, Parch, Sex_male)",0.036711,0.028563,0.014281
49,"(0, 2, 4, 5)","[0.784, 0.816, 0.824, 0.782258064516129, 0.782...",0.797703,"(Pclass, SibSp, Fare, Sex_male)",0.023638,0.018391,0.009196
46,"(0, 1, 4, 5)","[0.768, 0.816, 0.784, 0.782258064516129, 0.838...",0.797794,"(Pclass, Age, Fare, Sex_male)",0.033144,0.025787,0.012894
24,"(0, 1, 5)","[0.792, 0.824, 0.776, 0.7903225806451613, 0.83...",0.804206,"(Pclass, Age, Sex_male)",0.029976,0.023322,0.011661
43,"(0, 1, 2, 5)","[0.728, 0.824, 0.816, 0.8225806451612904, 0.85...",0.809084,"(Pclass, Age, SibSp, Sex_male)",0.054894,0.04271,0.021355
30,"(0, 4, 5)","[0.792, 0.808, 0.816, 0.8225806451612904, 0.81...",0.810619,"(Pclass, Fare, Sex_male)",0.013366,0.0104,0.0052
45,"(0, 1, 3, 5)","[0.784, 0.824, 0.8, 0.7983870967741935, 0.8467...",0.810632,"(Pclass, Age, Parch, Sex_male)",0.028493,0.022168,0.011084

In [46]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=0, criterion='gini')
rfc.fit(x_train, y_train)
for feature in zip(x_train.columns, rfc.feature_importances_):
    print(feature)

('Pclass', np.float64(0.08580548090109545))
('Age', np.float64(0.26433757901109173))
('SibSp', np.float64(0.05355992352286061))
('Parch', np.float64(0.03699908167792097))
('Fare', np.float64(0.28790097031129963))
('Sex_male', np.float64(0.2713969645757317))

In [47]:
from sklearn.feature_selection import SelectFromModel
sfm = SelectFromModel(estimator=rfc, threshold=0.2)
sfm = sfm.fit(x_train, y_train)
feature_names=x_train.columns
print('The most important features based on random forest classifier:')
for feature_list_index in sfm.get_support(indices=True):
    print('- ' + feature_names[feature_list_index])

The most important features based on random forest classifier:
- Age
- Fare
- Sex_male

In [48]:
from sklearn.metrics import accuracy_score
rfc_full = RandomForestClassifier(random_state=0, criterion='gini')
rfc_full.fit(x_train, y_train)
pred_full = rfc_full.predict(x_test)
print('The accuracy of classifier with full features: {:.2f}'.format(accuracy_score(y_test, pred_full)))

The accuracy of classifier with full features: 0.82

In [49]:
x_important_train = sfm.transform(x_train)
x_important_test = sfm.transform(x_test)

In [50]:
print(x_important_train.shape)
print(x_important_test.shape)

(623, 3)
(268, 3)

In [51]:
rfc_lim = RandomForestClassifier(random_state=0, criterion='gini')
rfc_lim.fit(x_important_train, y_train)
pred_lim = rfc_lim.predict(x_important_test)
print('The accuracy of classifier with limited features: {:.2f}'.format(accuracy_score(y_test, pred_lim)))

The accuracy of classifier with limited features: 0.80